### ISSUE TITLE
Suggestion: foreach loop choco install

### ISSUE THREAD

**Issue by tomasvanrijsse** [EdiWang/EnvSetup#2]
Thanks for your [article](https://edi.wang/post/2018/12/21/automate-windows-10-developer-machine-setup)!

I've got one minor suggestion;

We have a lot of choco to install, and the programmer's thinking is, of course, writing a loop, not copy of the command everywhere.  :wink:

**Comment by EdiWang** [comment]
Good idea! Thanks for your suggestion
